#!/usr/bin/env python3
import os
import sipconfig
from PyQt5.QtCore import PYQT_CONFIGURATION
basename = "PyCadCpp"

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = basename + ".sbf"

# Get the SIP configuration information.
config = sipconfig.Configuration()

cmd=[config.sip_bin, "-I",  "/usr/share/sip/PyQt5", "-e", "-c", "out"]
cmd+=PYQT_CONFIGURATION["sip_flags"].split(" ")
cmd+=["-b", build_file, basename + ".sip"]

# Run SIP to generate the code.
os.system(" ".join(cmd))
